# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=100, verbose_name='Componente activo')),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de marca')),
                ('registro', models.CharField(max_length=25, verbose_name='Registro sanitario')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componente-activo+', to='app.Activo')),
            ],
        ),
    ]
