# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='componente',
            field=models.CharField(max_length=100, unique=True, verbose_name='Componente activo'),
        ),
    ]
