# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170628_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentacion')),
                ('registro', models.CharField(max_length=25, verbose_name='Registro sanitario')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicina',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='medicina',
            name='registro',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='medicina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formato', to='app.Medicina'),
        ),
    ]
