# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170629_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='medicina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formato', to='app.Medicina'),
        ),
    ]
