# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170629_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de marca'),
        ),
    ]
