# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170629_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('clasificacion', models.CharField(max_length=10, verbose_name='Clasificacion')),
                ('medicina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medicina', to='app.Medicina')),
            ],
        ),
    ]
