# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='link',
            field=models.CharField(max_length=100, unique=True, verbose_name='Link'),
        ),
    ]
