# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170713_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de marca'),
        ),
    ]
